recipedatabase/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('recipes.urls')),
    path('admin/', admin.site.urls),
]

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'
urlpatterns = [
    path('', views.index, name='index'),
    path('recipe/<int:recipe_id>/', views.recipe_detail, name='recipe_detail'),
    path('ingredient/<int:ingredient_id>/', views.ingredient_detail, name='ingredient_detail'),
]

recipes/models.py
from django.db import models

class Recipe(models.Model):
    title = models.CharField(max_length=50)
    instructions = models.TextField()
    ingredients = models.ManyToManyField('Ingredient', blank=True)

    def __str__(self):
        return self.title

    def is_vegetarian(self):
        for recipe_ingredient in self.ingredients.all():
            if recipe_ingredient.isMeat:
                return False

        return True


class Ingredient(models.Model):
    name = models.CharField(max_length=50)
    isMeat = models.BooleanField()
    recipes = models.ManyToManyField(Recipe, blank=True)

    def __str__(self):
        return self.name

recipes/views.py
from django.shortcuts import render, get_object_or_404

from .models import Recipe, Ingredient

def index(request):
    recipe_list = Recipe.objects.all()
    context = {'recipe_list': recipe_list}
    return render(request, "recipes/index.html", context)

def recipe_detail(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    context = {'recipe': recipe}
    return render(request, 'recipes/recipe_detail.html', context)

def ingredient_detail(request, ingredient_id):
    ingredient = get_object_or_404(Ingredient, pk=ingredient_id)
    context = {'ingredient': ingredient}
    return render(request, 'recipes/ingredient_detail.html', context)

recipes/templates/recipes/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Stephen Smith Recipe Database</title>
  </head>
  <body>
    <div class="container">
      <h1>Recipes</h1>
      {% if recipe_list %}
        {% for recipe in recipe_list %}
          <a href="{% url 'recipes:recipe_detail' recipe.id %}">{{ recipe.title }}</a></br>
        {% endfor %}
      {% else %}
        <p>No recipes are available.</p>
      {% endif %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

recipes/templates/recipes/ingredient_detail.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Ingredient: {{ ingredient.name }}</title>
  </head>
  <body>
    <div class="container">
      <h1>{{ ingredient.name }}</h1>

      <h2>Recipes</h2>
      {% for recipe in ingredient.recipes.all %}
          <a href="{% url 'recipes:recipe_detail' recipe.id %}">{{ recipe.title }}</a><p>
      {% endfor %}

      <h2>Vegetarian?</h2>
      {% if ingredient.isMeat %}
          No
      {% else %}
          Yes
      {% endif %}

    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

recipes/templates/recipes/recipe_detail.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Recipe: {{ recipe.title }}</title>
  </head>
  <body>
    <div class="container">
      <h1>{{ recipe.title }}</h1>

      <h2>Ingredients</h2>
      {% for ingredient in recipe.ingredients.all %}
          <a href="{% url 'recipes:ingredient_detail' ingredient.id %}">{{ ingredient.name }}</a> </br>
      {% endfor %}

      <h2>Instructions</h2>
      {{ recipe.instructions }} <p>

      <h2>Vegetarian?</h2>
      {% if recipe.is_vegetarian %}
          Yes
      {% else %}
          No
      {% endif %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>